

POST http://localhost:3003/api/blogs 
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxnaGlnZ2lubyIsImlkIjoiNjE1MTA4NmRmYjdmZDYxN2Q2MDhjNDgyIiwiaWF0IjoxNjMyNzg2ODgwLCJleHAiOjE2MzI3OTA0ODB9.1plZgEkyfXaqDbP3SiKtej8x7J-IzttHXDycHvXqTFU

{
    "title": "Error saving to Cazuza", 
    "author": "Leonardo Ghiggino", 
    "url": "www.willthisshitwork.com", 
    "likes": "2021",
    "user": "614fa85e4e23ae24a4813b1e"
}


# cazuza = 614fa85e4e23ae24a4813b1e
#lghiggino = 6151086dfb7fd617d608c482